// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdcdplpakthvkllfqssh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkY2RwbHBha3RodmtsbGZxc3NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTQ3NDMsImV4cCI6MjA2Nzg5MDc0M30.n_X3OV-n_11NtWsivmjuzeIT-KdLqnw-fN5uxLagvTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});